    name: Reusable Workflow
    on: [push, pull_request]
    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: 14
        - name: Install dependencies
          run: npm i
        # - name: Run tests
        #   run: npm test

      docker-build:
        runs-on: ubuntu-latest
    
        needs: build
    
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
    
        - name: Build Docker image
          uses: docker/build-push-action@v2
          with:
            context: .
            file: Dockerfile
            push: true
            tags: hisham17785/node_pr:latest
