name: Caller Workflow

on: 
  push: 
    branches:
    - staging
  pull_request:
    branches:
    - staging

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Use main work flow to build the docker image
      uses: actions/checkout@v2
      with:
        repository: hishamfazlie/sample-node-project
        path: .github/workflows/main.yml@master
