name: Caller Workflow

on: 
  push: 
    branches:
    - staging
  pull_request:
    branches:
    - staging

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Use main work flow to build the docker image
      uses: sample-node-project/.github/workflows/main.yml@master
