name: Caller Workflow

on: 
  # workflow_dispatch:
  push:
    branches:
    - staging
  pull_request:
    branches:
    - staging

jobs:

  job1:
    # uses: HishamFazlie/workflows/.github/workflows/main-workflow-1.yml@main
    uses: HishamFazlie/workflows/.github/workflows/workflow-2.yml@main
    with:
      node-version: '18'
